# Practice 

In [1]:
A = 32 
b = 45
print(A+b)




77


In [ ]:
s = 15
m = 10

W = s + m
X = s - m
Y = s / m
Z = s * m

choice = input("Enter your Choice: W, X, Y, Z: ")

if choice == 'W':
    print("W =", W)
elif choice == 'X':
    print("X =", X)
elif choice == 'Y':
    print("Y =", Y)
elif choice == 'Z':
    print("Z =", Z)
else:
    print("Invalid choice. Please enter W, X, Y, or Z.")


# Operaters

1)Arthmatic opraters
2)comparision opraters
3)logical Opraterss
4)logical opraters
5)bitwise opraters
6)assignment opraters
7)identity opraters
8)membership opraters

# Arthmatic operaters


In [ ]:
a = 9
b = 4
print(a*b)
print(a-b)
print(a/b)
print(a+b)

In [ ]:
print(15+24)

In [ ]:
print(45-90)
print(78-34)

In [ ]:
print(a%b)

In [ ]:
print(a**b)

In [ ]:
print(a // b)

In [ ]:
print(a < b)

In [ ]:
print (a>b)

In [ ]:
print(a>=b)

In [ ]:
print (a<=b)

In [ ]:
print(a == b)

In [ ]:
print(a != b)

### Logical operaters

# *AND*
# *OR*
# *NOT*

In [ ]:
x =True
y = False

print( x and y)


In [ ]:
print(x or y)


In [ ]:
print( not y)

### Bitwise Operators

In [ ]:
x = 8 
y = 9
print(x & y)

In [ ]:
print ( x | y)

In [ ]:
print(x >> 9)

In [ ]:
print (y >> 3 )

In [ ]:
input(prompt = "Dipak")

In [ ]:
input()

In [ ]:
First_number = int(input("first number"))
Second_number = int(input("second number"))

print(First_number)
print(Second_number)

In [ ]:
#implicit
#explicit

In [ ]:
type(4 + 5.5)
4 + 5.5


In [ ]:
4 + 4.9 + 4j

In [ ]:
2.9 + 9.4 + 6.8j

In [ ]:
# int 

int("99")

In [ ]:
float('4')

In [ ]:
str(1)

In [ ]:
bool(0)

In [ ]:
bool(9)

In [ ]:
bool(9.6)

### Stirng Literels

In [ ]:
string = "this is python"
strings = "this is python"
char = "c"

multiline_str  = """This is multiline stirng more than one line"""
unicode = U"\U0001f600\U0001f606\U0001f923"
raw_str = r"raw \n  string"


print(string)
print(strings)
print(char)
print(multiline_str)
print(unicode)
print(raw_str)

### Boolean Literal

In [ ]:
a = True + 5
b = False + 9

print("a:", a)
print("b:", b)

###  Special Literal

In [ ]:
p = None
print(p)

In [ ]:
p = 45+ 54
print(p)

In [ ]:
# variable diclaration

p = None

# Oprataers

### If-Else  Statement

In [ ]:
# emailid - dipakjagadale@gmail.com
# password - 1234

mailid = input("Mail id")
password = input("password")

if mailid == dipakjagadale@gmail.com and password == 1234:
    print("welcome")
else:     
    print("incorrect credintials")

In [33]:
# emailid - dipakjagadale@gmail.com
# password - 1234

emailid = input("emailid")
if '@' in emailid:
    password = input ("Correct password")

    if emailid == "dipakjagadale@gmail.com" and password == "1234":
        print("welcome")
    elif emailid == 'dipakjagadale@gmail.com' and password != "1234":
         print("password incorrect")
            password = input("Reenter password")
        if password == "1234":
             print("Finally corect")
        else :
             print("Still incorrect")
    else:
        print("incorrect creditials")
        
else:
    print("Incorrect email")
        

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 13)

### String

## common Fuction
### len
### max
### mean
### fuction

In [2]:
c = "Dipak"
len (c)

5

In [3]:
max (c)


'p'

In [4]:
min (c)

'D'

In [7]:
sorted(c,reverse = True)

['p', 'k', 'i', 'a', 'D']

### 1.Capitalize/Title/Upper/Lower/swapcase

In [9]:
"it is raining today".capitalize()

'It is raining today'

In [13]:
"it is raining today" . title()

'It Is Raining Today'

In [15]:
c.upper().lower()

'dipak'

In [16]:
"kolkata".swapcase()

'KOLKATA'

# 2. count



In [19]:
"it is raining".count("n")

2

### 3 .Find/index

In [21]:
"it is raining". index("n")

9

### 4.Endswith/startswith

In [27]:
"it is raining" .endswith("raining")

True

In [26]:
"it is raining ". startswith("t")

False

### 5. Format

In [28]:
"Hello my name is {} and i am {}". format("Dipak",30)

'Hello my name is Dipak and i am 30'

In [29]:
"Hello my name is {} and i am {}". format("Dipak",30)

'Hello my name is Dipak and i am 30'

In [50]:
str1 = "i am a new data scientist"
str2 = str1.split(" ")
print(str2)




['i', 'am', 'a', 'new', 'data', 'scientist']


In [42]:
# Splitting a string using a space as the delimiter
sentence = "Hello,World,How,Are,You"
words = sentence.split (" ")
print(words)

['Hello,World,How,Are,You']


In [ ]:
Numpy:
Numpy- is a Numerical Python

It is developed by Travis Oliphant in 2005

Numpy has functions to work on linear algebra, fourier transform, and matrices

Its basically used to work with array, It can work with multidimentional Arrays

Why:
Numpy is built using python, and most of the part which requires fatser execution is developed using c or c++,So it is very fast in execution.

Numpy arrays are called as ndarray

Numpy has 50x speed as compared to python list, because NumPy is faster than lists because it uses vectorized operations, optimized C code, memory efficiency, and cache efficiency. These features allow NumPy to perform calculations on large amounts of data more quickly and efficiently than lists.

Numpy provides lots of functions which can be performed on large data

Numpy gives faster response as compared to list as it stores numpy arrays at one continuous location whereas lists are stored in scattered locations

In [46]:
import keyword
print(keyword.kwlist)
len(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


35

In [51]:
"$".join(str2)

'i$am$a$new$data$scientist'

In [52]:
str1

'i am a new data scientist'

In [60]:
str1.title()

'I Am A New Data Scientist'

In [61]:
str1

'i am a new data scientist'

In [62]:
str1.replace("i","I")

'I am a new data scIentIst'

In [63]:
import numpy as np


In [65]:
np.__version__


'1.24.2'

### Array:  collection of similar data type

In [4]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [8]:
arr1 = arr.reshape(7,1)
arr1


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [16]:
arr2 = np.arange(15)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr2.reshape(5,3)
arr2.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
arrr = np.array([1,2,3,4,5])
arrr, arrr.ndim

(array([1, 2, 3, 4, 5]), 1)

In [24]:
arr5 = np.array([[1,2,3]])
arr5,arr5.ndim

(array([[1, 2, 3]]), 2)